# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Muhammad Bilal Shahid
title: Graduate Research Assistant
email: mbilalshahed@gmail.com
#website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: MBilal_Shahid
github_username:  mbelalsh
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: bilal_klair
#linkedin_username: jameswgrant
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Muhammad Bilal Shahid and I'm a graduate research assistat in microfabrication at Incheon National University. I am passionate about physics informed learning and thus have some experience applying to some of the projects in my laboratory. Apart from that, I have worked at a number of projects as part of the courses that I completed earlier this year. The repositeries of those projects can be found on my Github profile.

  I am most skilled in: <mark>Keras</mark>, <mark>Tensorflow</mark> and some other python libraries.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
